SET SCHEMA FN71924;
CREATE TABLE BOOKSTORE(
    NAME VARCHAR(50)  NOT NULL PRIMARY KEY ,
    ADDRESS VARCHAR(70) NOT NULL

);
CREATE TABLE STAFF(
    STAFF_NUMBER INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NAME VARCHAR(50) NOT NULL,
    STAFF_PHONE_NUMBER CHAR(10) NOT NULL,
    BOOKSTORE_NAME VARCHAR(50) REFERENCES BOOKSTORE(NAME)
);
CREATE TABLE CLIENT(
    CARD_NUMBER INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 10000 INCREMENT BY 1),
    CLIENT_NAME VARCHAR(50) NOT NULL,
    CLIENT_PHONE_NUMBER CHAR(10) NOT NULL,
    EMAIL VARCHAR(20) CHECK(EMAIL LIKE '%_@_%.__%'),
    BOOKSTORE_NAME VARCHAR(50) REFERENCES BOOKSTORE(NAME)
);
CREATE TABLE BOOK(
    SERIAL_NUMBER INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 1),
    BOOK_NAME VARCHAR(50) NOT NULL,
    DISCOUNT INTEGER CHECK(DISCOUNT > 0 AND DISCOUNT <100),
    RATING DECIMAL(1,2) CHECK(RATING >= 0 AND RATING <= 5),
    SUMMARY CLOB NOT NULL,
    PRICE DECIMAL(5, 1),
    INVENTORY_LEFT INTEGER,
    PUBLISHING_HOUSE VARCHAR(20) NOT NULL,
    AUTHOR_NAME VARCHAR(40) NOT NULL,
    GENRE VARCHAR(10) NOT NULL,
    PUBLISHING_YEAR INT CHECK(PUBLISHING_YEAR > 0),
    CLIENT_NUMBER VARCHAR(10) REFERENCES CLIENT(CARD_NUMBER)

)